# Generated by Django 4.1.3 on 2022-11-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nota', models.CharField(max_length=200, verbose_name='Nota')),
                ('fecha_pago', models.DateField()),
                ('fecha_Vencimiento', models.DateField()),
                ('valor_Pago', models.CharField(max_length=200, verbose_name='Valor del Pago')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'Evento',
            },
        ),
    ]
