# Generated by Django 4.1.4 on 2022-12-13 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripciones')),
                ('valor_Pago', models.CharField(max_length=200, verbose_name='Valor del Pago')),
                ('fecha_pago', models.DateField(null=True, verbose_name='Fecha de pago')),
                ('fecha_Vencimiento', models.DateField(null=True, verbose_name='Valido Hasta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='Ip del Cliente')),
                ('cedula', models.CharField(max_length=12, unique=True, verbose_name='Cedula del Cliente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del Cliente')),
                ('telefono_uno', models.CharField(max_length=12, verbose_name='Primer Telefono ')),
                ('telefonos_dos', models.CharField(blank=True, max_length=12, null=True, verbose_name='Segundo Telefono')),
                ('mensualidad', models.CharField(max_length=100, null=True, verbose_name='Mensualidad')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalacion')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('vereda', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vereda')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('id_Estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='home.estado')),
                ('id_Municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Municipio', to='home.municipio')),
                ('id_Pueblo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pueblo', to='home.pueblo')),
                ('pagos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.pago', verbose_name='Datos de Pago')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['ip'],
            },
        ),
    ]
