# Generated by Django 4.1.3 on 2022-11-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_lugar_residencia_descripcion_and_more'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_Estado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Id_Estado', to='home.estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_lugar_Residencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Id_Residencia', to='home.lugar_residencia'),
        ),
    ]
