# Generated by Django 4.1.3 on 2022-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='fecha_Instalacion',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripciones'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_Vencimiento',
            field=models.DateField(null=True, verbose_name='Valido Hasta'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_pago',
            field=models.DateField(null=True, verbose_name='Fecha de pago'),
        ),
    ]
