# Generated by Django 4.1.4 on 2022-12-13 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pagos',
        ),
        migrations.AddField(
            model_name='pago',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='cliente.cliente'),
        ),
    ]
