# Generated by Django 4.1.3 on 2022-11-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_Pago',
            field=models.DateField(null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valido',
            field=models.DateField(null=True, verbose_name='Valido Hasta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_Pago',
            field=models.CharField(max_length=100, null=True, verbose_name='Valor de pago'),
        ),
    ]
