# Generated by Django 4.1.4 on 2022-12-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_pagos_pago_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_instalacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Instalacion'),
        ),
    ]
