# Generated by Django 4.1.3 on 2022-11-18 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('cliente', '0002_cliente_fecha_pago_cliente_valido_cliente_valor_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_Instalacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_Pago',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='valido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='valor_Pago',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_Estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Id_Estado', to='home.estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_lugar_Residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Id_Residencia', to='home.lugar_residencia'),
        ),
    ]
