# Generated by Django 4.1.3 on 2022-11-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_agenda_fecha_instalacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_instalacion',
            field=models.DateField(null=True, verbose_name='Fecha de Instalacion'),
        ),
    ]
