# Generated by Django 4.1.3 on 2022-11-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_remove_cliente_fecha_instalacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripciones')),
                ('valor_Pago', models.IntegerField(verbose_name='Valor del pago')),
                ('fecha_pago', models.DateTimeField(null=True, verbose_name='Fecha de pago')),
                ('fecha_Vencimiento', models.DateTimeField(null=True, verbose_name='Valido Hasta')),
                ('fecha_Instalacion', models.DateField(null=True, verbose_name='Fecha de Instalacion')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'db_table': 'Agenda',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.agenda', verbose_name='Datos de Fecha'),
        ),
    ]
