# Generated by Django 4.1.3 on 2022-11-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_fecha_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Instalacion'),
        ),
    ]
