# Generated by Django 4.1.4 on 2022-12-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_fecha_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mensualidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mensualidad'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='valor_Pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor del Pago'),
        ),
    ]
