# Generated by Django 4.1.4 on 2022-12-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_mensualidad_alter_pago_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='valor_Pago',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Valor del Pago'),
        ),
    ]
