# Generated by Django 4.1.3 on 2022-11-22 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
        ('cliente', '0004_agenda_cliente_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.agenda', verbose_name='Datos de Pago'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_Cartera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cartera', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_Estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='home.estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_Municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Municipio', to='home.municipio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_lugar_Residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Residencia', to='home.lugar_residencia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_soporte_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SoporteTecnico', to=settings.AUTH_USER_MODEL),
        ),
    ]
