# Generated by Django 4.1.4 on 2022-12-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_pago_fecha_pago_alter_pago_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_Vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Valido Hasta'),
        ),
    ]
