# Generated by Django 4.1.3 on 2022-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_agenda_alter_cliente_id_cartera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='valor_Pago',
            field=models.CharField(max_length=200, verbose_name='Valor del Pago'),
        ),
    ]
