# Generated by Django 4.1.4 on 2022-12-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_pago_fecha_vencimiento_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_Vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Valido Hasta'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de pago'),
        ),
    ]
