# Generated by Django 4.1.4 on 2022-12-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_alter_pago_fecha_vencimiento_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Instalacion'),
        ),
    ]
