# Generated by Django 4.1.4 on 2022-12-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_cliente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mensualidad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mensualidad'),
        ),
    ]
