# Generated by Django 4.1.3 on 2022-11-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_rename_nombre_event_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fecha_Pago',
        ),
        migrations.RemoveField(
            model_name='event',
            name='valido',
        ),
        migrations.RemoveField(
            model_name='event',
            name='valor_Pago',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='Valido Hasta'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='Fecha de pago'),
        ),
    ]
