# Generated by Django 4.1.4 on 2022-12-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='pueblo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Pueblo')),
            ],
            options={
                'verbose_name': 'Pueblo',
                'verbose_name_plural': 'Pueblos',
                'db_table': 'pueblo',
                'ordering': ['id'],
            },
        ),
    ]
