# Generated by Django 4.1.3 on 2022-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar_residencia',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='lugar_residencia',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='lugar_residencia',
            name='pueblo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del pueblo'),
        ),
        migrations.AlterField(
            model_name='lugar_residencia',
            name='vereda',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vereda'),
        ),
    ]
